<!DOCTYPE html>
<!--PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

	<!--EXTERNAL STYLE SHEET-->
	<link rel="stylesheet" href="css/lib/global.css" type="text/css" media="screen" />

	<!--META TAGS FOR WEBAPP-->
	<meta name="apple-mobile-web-app-capable" content="yes">

	<!--ICON FOR GENERAL WEB PAGE-->
	<link rel="icon" href="img/favicon.png" />

	<!--ICON FOR IPHONE BOOKMARKS-->
	<link rel="apple-touch-icon" href="img/favicon.png" />

	<!--GOOGLE FONTS-->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

	<script type="text/javascript" src="js/lib/jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="js/lib/utils.js"></script>

	<script type="text/javascript">
	function fixBG(){
		var asp = $(document).width() / $(document).height();
		if(asp > 1.87) $("body").css("background-size","100% auto");
		else $("body").css("background-size","auto 100%");
	}

	$(document).ready(function(){
		//$(".content-area").animate({opacity:1},1200);

		$("a").click(function(){
			window.location = this.getAttribute("href");
			return false;
		});

		fixBG();
		$(window).resize(fixBG);
	});
	</script>

	<link rel="stylesheet" href="css/lib/standard_gs_styles.css" />
	<link rel="stylesheet" href="css/styles.css" />
	<title> Scott Mathias Sarsfield's Web Site </title>

	<!--Game Script-->
	<script src="js/gameplay.js"></script>

</head>
<body>
	<div id="main_nav_bar">

		<div class="page-logo">
			<a href="http://scottmsarsfield.com">
				<img src="holmes.gif" alt="Scott M Sarsfield's Website" />
				<span>Scott Mathias Sarsfield's Website</span>
			</a>
		</div>
	</div>


	<div class="page-title">
		<span>Sherlock X</span>
	</div>

	<div class="content-area"><div>

		<div class="content">
			<img class="game-screenshot" alt="Sherlock X" src="img/gs_screenshot.png">
			<div class="game-description">
				<p><span style="font-weight:bold">Sherlock X</span> is a number and card guessing "game" that will determine what
					number card you have based on your responses to a series of "Is it shown?" prompts.
					It uses binary search as its foundational concept.
				</p>
			</div>
		</div>

		<input class="game-launch-button" type="button" onclick="launchGame(1) " value="Launch Numbers" />
		<input class="game-launch-button" type="button" onclick="launchGame(2) " value="Launch Cards" />


	</div></div>

	<div id="main_footer">
		<span>
			<!--Do not touch the code below-->
			The content of these web pages is not generated by and does not represent the
			views of Santa Clara University or any of its departments or organizations.

			<!--End Of Warning-->
		</span>
	</div>
	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-41039160-1', 'scu.edu');
	ga('send', 'pageview');

	</script>
</body>
</html>
